jenkins:
  systemMessage: "Scheme Jenkins"
  numExecutors: 0
  nodes:
    - permanent:
        mode: NORMAL
        name: "agent1"
        labelString: "docker"
        numExecutors: 8
        remoteFS: "/home/jenkins/agent"
        launcher:
          SSHLauncher:
            host: "jenkins-agent"
            port: 22
            credentialsId: agent_ssh
            launchTimeoutSeconds: 60
            maxNumRetries: 3
            retryWaitTime: 30
            sshHostKeyVerificationStrategy:
              manuallyTrustedKeyVerificationStrategy:
                requireInitialManualTrust: false
  authorizationStrategy:
    projectMatrix:
      entries:
      - group:
          name: "authenticated"
          permissions:
          - "Job/Read"
          - "Overall/Read"
      - user:
          name: "admin"
          permissions:
          - "Overall/Administer"
      - user:
          name: "anonymous"
          permissions:
          - "Job/Read"
          - "Overall/Read"
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         name: admin
         password: "${readFile:/secrets/adminpassword}"

appearance:
  pipelineGraphView:
    showGraphOnBuildPage: true
    showGraphOnJobPage: true

credentials:
  system:
    domainCredentials:
       - credentials:
           - basicSSHUserPrivateKey:
               scope: GLOBAL
               id: agent_ssh
               username: "jenkins"
               description: "SSH key for jenkins agent"
               privateKeySource:
                 directEntry:
                   privateKey: "${readFile:/secrets/id_rsa}"

jobs:
  - script: >
      folder('index_scheme_org') {
        displayName: 'index.scheme.org'
      }
  - script: >
      multibranchPipelineJob('index_scheme_org/build') {
        displayName: 'Build and deploy'
        branchSources {
          git {
              id('github')
              remote('https://github.com/schemeorg-community/index.scheme.org')
          }
        }
        orphanedItemStrategy {
          discardOldItems {
              numToKeep(10)
          }
        }
      }
